// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdjustmentsVerticalIcon: typeof import('@heroicons/vue/24/solid')['AdjustmentsVerticalIcon']
    AlfastoreBrand: typeof import('./components/AlfastoreBrand.vue')['default']
    ArrowSmRightIcon: typeof import('@heroicons/vue/24/solid')['ArrowSmRightIcon']
    Bars3CenterLeftIcon: typeof import('@heroicons/vue/24/solid')['Bars3CenterLeftIcon']
    BarsArrowDownIcon: typeof import('@heroicons/vue/24/solid')['BarsArrowDownIcon']
    CardProduct: typeof import('./components/CardProduct.vue')['default']
    ChevronLeftIcon: typeof import('@heroicons/vue/24/solid')['ChevronLeftIcon']
    ChevronRightIcon: typeof import('@heroicons/vue/24/solid')['ChevronRightIcon']
    MagnifyingGlassIcon: typeof import('@heroicons/vue/24/solid')['MagnifyingGlassIcon']
    MdiFacebook: typeof import('./components/icons/MdiFacebook.vue')['default']
    MdiInstagram: typeof import('./components/icons/MdiInstagram.vue')['default']
    MdiWhatsapp: typeof import('./components/icons/MdiWhatsapp.vue')['default']
    PhoneIcon: typeof import('@heroicons/vue/24/solid')['PhoneIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarIcon: typeof import('@heroicons/vue/24/solid')['StarIcon']
    WebFooter: typeof import('./components/WebFooter.vue')['default']
    WebNavbar: typeof import('./components/WebNavbar.vue')['default']
    XMarkIcon: typeof import('@heroicons/vue/24/solid')['XMarkIcon']
  }
}
